--- 
AfterInstall: 
  - 
    location: "scripts / change_permissions.sh"
ApplicationStart: 
  - 
    location: "scripts / start_server.sh"
ApplicationStop: 
  - 
    location: "scripts / stop_server.sh"
BeforeInstall: 
  - 
    location: "scripts / install_dependencies.sh"
Destination: "/ opt / CodeDeployDemo"
Files: 
  - 
    source: /
Hooks: ~
Os: linux
Runas: root
Timeout: 300
Version: 0.0
